### ISSUE TITLE
`OS Error: The filename, directory name, or volume label syntax is incorrect` on windows, unrelated to package core, but compatibility issues about folder paths

### ISSUE THREAD

**Issue by liudonghua123** [fzyzcjy/dart_interactive#30]
I tried the guidance on readme (`Inside packages/interactive, execute dart run --enable-vm-service bin/interactive.dart.`), however, it not works for me.

```shell
D:\code\dart>git clone git@github.com:fzyzcjy/dart_interactive.git
Cloning into 'dart_interactive'...
remote: Enumerating objects: 820, done.
remote: Counting objects: 100% (368/368), done.
remote: Compressing objects: 100% (205/205), done.
remote: Total 820 (delta 141), reused 344 (delta 120), pack-reused 452
Receiving objects: 100% (820/820), 141.04 KiB | 300.00 KiB/s, done.
Resolving deltas: 100% (318/318), done.

D:\code\dart>cd dart_interactive\

D:\code\dart\dart_interactive>cd packages\interactive\

D:\code\dart\dart_interactive\packages\interactive>
D:\code\dart\dart_interactive\packages\interactive>dart run --enable-vm-service bin\interactive.dart
The Dart VM service is listening on http://127.0.0.1:8181/QttPLrcLj-Y=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/QttPLrcLj-Y=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2FQttPLrcLj-Y%3D%2Fws
Error: Couldn't resolve the package 'interactive' in 'package:interactive/src/main.dart'.
bin/interactive.dart:1:8: Error: Not found: 'package:interactive/src/main.dart'
import 'package:interactive/src/main.dart' as lib_main;
       ^
bin/interactive.dart:3:42: Error: Method not found: 'main'.
void main(List<String> args) => lib_main.main(args);
                                         ^^^^

D:\code\dart\dart_interactive\packages\interactive>dart pub get
Resolving dependencies...
+ _fe_analyzer_shared 49.0.0
+ analyzer 5.1.0
+ args 2.3.1
+ async 2.9.0
+ boolean_selector 2.1.0
+ cli_repl 0.2.3
+ collection 1.17.0
+ convert 3.0.2
+ coverage 1.6.1
+ crypto 3.0.2
+ file 6.1.4
+ frontend_server_client 3.1.0
+ glob 2.1.0
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.3
+ js 0.6.5
+ lint 1.10.0
+ logging 1.1.0
+ matcher 0.12.12
+ meta 1.8.0
+ mime 1.0.2
+ node_preamble 2.0.1
+ package_config 2.1.0
+ path 1.8.2
+ pool 1.5.1
+ pub_semver 2.1.1
+ shelf 1.4.0
+ shelf_packages_handler 3.0.1
+ shelf_static 1.1.1
+ shelf_web_socket 1.0.2
+ source_map_stack_trace 2.1.0
+ source_maps 0.10.11
+ source_span 1.9.1
+ stack_trace 1.11.0
+ stream_channel 2.1.1
+ string_scanner 1.1.1
+ term_glyph 1.2.1
+ test 1.21.6
+ test_api 0.4.14
+ test_core 0.4.18
+ typed_data 1.3.1
+ vm_service 9.4.0
+ watcher 1.0.2
+ web_socket_channel 2.2.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.1
Downloading test 1.21.6...
Downloading lint 1.10.0...
Downloading logging 1.1.0...
Downloading collection 1.17.0...
Downloading cli_repl 0.2.3...
Downloading test_core 0.4.18...
Downloading test_api 0.4.14...
Downloading analyzer 5.1.0...
Downloading _fe_analyzer_shared 49.0.0...
Downloading stream_channel 2.1.1...
Downloading stack_trace 1.11.0...
Downloading js 0.6.5...
Downloading source_maps 0.10.11...
Downloading watcher 1.0.2...
Downloading http_parser 4.0.2...
Downloading frontend_server_client 3.1.0...
Downloading shelf 1.4.0...
Downloading coverage 1.6.1...
Changed 47 dependencies!

D:\code\dart\dart_interactive\packages\interactive>dart run --enable-vm-service bin/interactive.dart
The Dart VM service is listening on http://127.0.0.1:8181/56H0eTNIIls=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/56H0eTNIIls=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A8181%2F56H0eTNIIls%3D%2Fws
Unhandled exception:
FileSystemException: Exists failed, path = 'C:\Users\LIUD~1.H\AppData\Local\Temp/dart_interactive_workspace_2022-10-22T22:38:56.335037' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
#0      _Directory.existsSync (dart:io/directory_impl.dart:94:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:126:11)
#2      WorkspaceFileTree._prepare (package:interactive/src/workspace_file_tree.dart:31:20)
#3      WorkspaceFileTree.create (package:interactive/src/workspace_file_tree.dart:14:11)
<asynchronous suspension>
#4      run (package:interactive/src/main.dart:30:29)
<asynchronous suspension>

D:\code\dart\dart_interactive\packages\interactive>
D:\code\dart\dart_interactive\packages\interactive>dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "windows_x64"

D:\code\dart\dart_interactive\packages\interactive>ver

Microsoft Windows [Version 10.0.22621.675]

D:\code\dart\dart_interactive\packages\interactive>
```

**Comment by fzyzcjy** [comment]
This is the problem: FileSystemException: Exists failed, path = 'C:\Users\LIUD~1.H\AppData\Local\Temp/dart_interactive_workspace_2022-10-22T22:38:56.335037' (OS Error: The filename, directory name, or volume label syntax is incorrect.

I should use "\" not "/", i.e. use path join instead of hardcoding "/". Will fix today.

**Comment by fzyzcjy** [comment]
Will fix this after CI is configured in order to verify CI correctness as well

**Comment by fzyzcjy** [comment]
https://github.com/fzyzcjy/dart_interactive/actions/runs/3305144365/jobs/5455011709

reproduced and fixed

**Comment by fzyzcjy** [comment]
FileSystemException: Exists failed, path = 'C:\Users\RUNNER~1\AppData\Local\Temp\dart_interactive_workspace_2022-10-23T00:17:14.630661' (OS Error: The filename, directory name, or volume label syntax is incorrect.

**Comment by fzyzcjy** [comment]
Hmm I do not have a windows at hand. Could you please debug it a little bit? It seems unrelated to the core of this package, but instead, only related to creating folders etc.

**Comment by fzyzcjy** [comment]
I will try to remove ":" etc now

**Comment by fzyzcjy** [comment]
it works

**Comment by fzyzcjy** [comment]
8181 is probably because you already start one, and do not stop/kill it

**Comment by fzyzcjy** [comment]
Weird. I suspect it is run twice. i.e. interactive calls interactive calls interactive (originally should be: interactive calls interactive, where the latter has vm serviice enabled)

**Comment by fzyzcjy** [comment]
Oh I see, please do *not* use dart run!

**Comment by fzyzcjy** [comment]
use new syntax here: https://github.com/fzyzcjy/dart_interactive#-getting-started

**Comment by fzyzcjy** [comment]
great!
